### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'get')

### ISSUE THREAD

**Issue by kristaum** [grafana/grafana-amazonprometheus-datasource#291]
**What happened**: Trying to query for data through explore or creating a dashboard and error "TypeError: Cannot read properties of undefined (reading 'get')" is presented

**What you expected to happen**: To be able to query prometheus data from amazon managed prometheus source.

**How to reproduce it (as minimally and precisely as possible)**:
Install plugin
Add as datasource
Save & Test
click on either building a dashboard or Explore view links

![Image](https://github.com/user-attachments/assets/2a99d2e0-4e6d-453a-b4c7-7dd5bb140e23)

**Anything else we need to know?**:

**Environment**:

- Grafana version: 11.0.0
- Plugin version: 1.0.2
- OS Grafana is installed on: EKS 1.29.8
- User OS & Browser: MacOS/Chrome

**Comment by idastambuk** [comment]
HI @kristaum, I managed to reproduce the error on plugin v1.0.2 but not on 1.0.3. If you update the plugin, does the error still appear?

**Comment by kristaum** [comment]
Hi @idastambuk thanks for the response, I ended up upgrading grafana from 11.0.0 to 11.3.0 and that solved the issue. Will try 1.0.3 some time.
