### ISSUE TITLE
Grafana Amazon Prometheus Datasource Plugin v1.0.3 - TypeError: Cannot Read Properties of Undefined (reading 'get')

### ISSUE THREAD

**Issue by hkjs96** [grafana/grafana-amazonprometheus-datasource#299]
**What happened**: 
When trying to explore the data source grafana-amazonprometheus-datasource, an error occurred:
TypeError: Cannot read properties of undefined (reading 'get').
This error appears to be related to the Amazon Managed Service for Prometheus data source plugin.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Screenshots**
![Image](https://github.com/user-attachments/assets/d66acd46-e4cd-4124-abbf-89ff8371bbf3)

**Anything else we need to know?**:

**Environment**:

- Grafana version: Grafana Enterprise 11.1.3
- Plugin version: 1.0.3
- OS Grafana is installed on: Amazon Linux 2023
- User OS & Browser: Window , Chrome
- Others: I am currently using Grafana Amazon Prometheus Datasource Plugin version 1.0.1 after downgrading from version 1.0.3 due to issues.

**Comment by idastambuk** [comment]
Hi @hkjs96 are you able to update Grafana to 11.3.0 and if so, does the error still happen?

**Comment by hkjs96** [comment]
Hello, @idastambuk  when testing with Grafana version 11.3.1, there are no issues with the Amazon Prometheus Datasource Plugin version 1.0.3.
